name: OSSAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '29 2 * * 0'

permissions:
  contents: read

jobs:
  OSSAR-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OSSAR
        id: ossar
        uses: github/ossar-action@v1

      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}
